#include <juce_core/juce_core.h>
#include <juce_events/juce_events.h>
#include <iostream>
#include <memory>

// Qt Includes
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQuickWindow>
#include <QQmlContext>
#include <QFont>
#include <QIcon>
#include <QSize>
#include <QtGlobal>

#include "DjEngine.h"
#include "WaveformItem.h"
#include "library/LibraryManager.h"
#include "library/CoverArtProvider.h"
#include "fx/FxManager.h"
#include "link/LinkManager.h"
#include "SystemMonitor.h"
#include "midi/ParameterStore.h"
#include "midi/MidiControllerManager.h"
#include "SettingsManager.h"
#include "library/LibraryDatabase.h"
#include "library/LibraryTableModel.h"

using namespace Qt::StringLiterals;

namespace {
QtMessageHandler g_previousMessageHandler = nullptr;
const QString kBreezeDialOverrideWarning = QStringLiteral("Member fillColor of the object BreezeDial overrides a member of the base object");

void filteredMessageHandler(QtMsgType type, const QMessageLogContext& context, const QString& message)
{
    if (message.contains(kBreezeDialOverrideWarning))
        return;

    if (g_previousMessageHandler)
        g_previousMessageHandler(type, context, message);
}
}

int main(int argc, char *argv[])
{
    std::cout << "========================================" << std::endl;
    std::cout << "RAMSBROCK DJ ENGINE - INITIAL BUILD TEST" << std::endl;
    std::cout << "JUCE Version:   " << juce::SystemStats::getJUCEVersion() << std::endl;
    std::cout << "C++ Standard:   " << __cplusplus << std::endl;
    std::cout << "========================================" << std::endl;

    qDebug() << "Essentia disabled by project policy; using internal analysis pipeline.";

    g_previousMessageHandler = qInstallMessageHandler(filteredMessageHandler);
#if QT_VERSION >= QT_VERSION_CHECK(6, 7, 0)
    QQuickWindow::setTextRenderType(QQuickWindow::CurveTextRendering);
#else
    QQuickWindow::setTextRenderType(QQuickWindow::QtTextRendering);
#endif

    if (qEnvironmentVariableIsEmpty("QT_QUICK_CONTROLS_STYLE"))
        qputenv("QT_QUICK_CONTROLS_STYLE", "Basic");

    if (qEnvironmentVariableIsEmpty("QT_SCALE_FACTOR_ROUNDING_POLICY"))
        qputenv("QT_SCALE_FACTOR_ROUNDING_POLICY", "RoundPreferFloor");

    if (qEnvironmentVariableIsEmpty("QT_LOGGING_RULES")) {
        qputenv("QT_LOGGING_RULES",
                "qt.scenegraph.general=false;"
                "qt.rhi.general=false");
    }

#if !defined(Q_OS_MACOS)
    // Enforce Vulkan on Linux/Windows.
    const QString rhiBackend = qEnvironmentVariable("QSG_RHI_BACKEND");
    if (rhiBackend.compare("vulkan", Qt::CaseInsensitive) != 0)
        qputenv("QSG_RHI_BACKEND", "vulkan");
    QQuickWindow::setGraphicsApi(QSGRendererInterface::Vulkan);
#endif
    QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::RoundPreferFloor);

    QGuiApplication app(argc, argv);

    // Load app icon from embedded QRC (generated by scripts/generate_icons.sh).
    // Multiple sizes let Qt pick the sharpest one for each use (taskbar, title bar, dock).
    {
        QIcon appIcon;
        for (int sz : {16, 32, 48, 64, 128, 256, 512}) {
            const QString path = QStringLiteral(":/icons/%1.png").arg(sz);
            appIcon.addFile(path, QSize(sz, sz));
        }
        if (!appIcon.isNull())
            app.setWindowIcon(appIcon);
    }

    // Set a global default font with proper hinting strategy
    QFont defaultFont = app.font();
    defaultFont.setHintingPreference(QFont::PreferFullHinting);
    defaultFont.setStyleStrategy(QFont::PreferAntialias);
    app.setFont(defaultFont);

    juce::ScopedJuceInitialiser_GUI juceInit;

    SettingsManager::getInstance().init();

    auto& settingsManager = SettingsManager::getInstance();

    auto deckA = std::make_unique<DjEngine>();
    auto deckB = std::make_unique<DjEngine>();

    deckA->applyAudioDeviceSettings(settingsManager.getAudioMasterDeviceType(),
                                    settingsManager.getAudioMasterOutputDevice(),
                                    settingsManager.getAudioSampleRate(),
                                    settingsManager.getAudioBufferSize(),
                                    settingsManager.getAudioMasterFirstChannel(),
                                    settingsManager.getAudioHeadphonesFirstChannel(),
                                    settingsManager.getAudioBoothFirstChannel());

    auto coverProvider = std::make_unique<CoverArtProvider>();
    deckA->setCoverArtProvider(coverProvider.get(), "deckA");
    deckB->setCoverArtProvider(coverProvider.get(), "deckB");

    QQmlApplicationEngine engine;

    ParameterStore parameterStore;
    MidiControllerManager midiManager(&parameterStore);

    // Route MIDI parameter changes to the appropriate deck controls.
    // Volume and crossfader are handled by MixerSection.qml via parameterStore.
    // Button events: value > 0 = press/on, value == 0 = release/off.
    QObject::connect(&parameterStore, &ParameterStore::parameterChanged,
        [deckAPtr = deckA.get(), deckBPtr = deckB.get()](const QString& id, float value)
    {
        if (id == "deckA_play") { if (value > 0.0f) deckAPtr->togglePlay(); }
        else if (id == "deckB_play") { if (value > 0.0f) deckBPtr->togglePlay(); }
        else if (id == "deckA_cue") {
            if (value > 0.0f) deckAPtr->cueButtonPress();
            else              deckAPtr->cueButtonRelease();
        }
        else if (id == "deckB_cue") {
            if (value > 0.0f) deckBPtr->cueButtonPress();
            else              deckBPtr->cueButtonRelease();
        }
        // Trim: MIDI 0-1 → engine 0-2 (center = 1.0 = unity)
        else if (id == "deckA_gain")   deckAPtr->setTrim(static_cast<double>(value) * 2.0);
        else if (id == "deckB_gain")   deckBPtr->setTrim(static_cast<double>(value) * 2.0);
        // EQ/filter: MIDI 0-1 → engine -1 to +1 (center = 0.0)
        else if (id == "deckA_eqHigh") deckAPtr->setEqHigh(static_cast<double>(value) * 2.0 - 1.0);
        else if (id == "deckB_eqHigh") deckBPtr->setEqHigh(static_cast<double>(value) * 2.0 - 1.0);
        else if (id == "deckA_eqMid")  deckAPtr->setEqMid(static_cast<double>(value) * 2.0 - 1.0);
        else if (id == "deckB_eqMid")  deckBPtr->setEqMid(static_cast<double>(value) * 2.0 - 1.0);
        else if (id == "deckA_eqLow")  deckAPtr->setEqLow(static_cast<double>(value) * 2.0 - 1.0);
        else if (id == "deckB_eqLow")  deckBPtr->setEqLow(static_cast<double>(value) * 2.0 - 1.0);
        else if (id == "deckA_filter") deckAPtr->setFilter(static_cast<double>(value) * 2.0 - 1.0);
        else if (id == "deckB_filter") deckBPtr->setFilter(static_cast<double>(value) * 2.0 - 1.0);
        // Tempo fader: MIDI 0-1 → engine -8% to +8%
        else if (id == "deckA_tempo")  deckAPtr->setTempoPercent(static_cast<double>(value) * 16.0 - 8.0);
        else if (id == "deckB_tempo")  deckBPtr->setTempoPercent(static_cast<double>(value) * 16.0 - 8.0);
    });

    engine.addImageProvider("coverart", coverProvider.release());

    engine.rootContext()->setContextProperty("settingsManager", &settingsManager);
    engine.rootContext()->setContextProperty("deckA", deckA.get());
    engine.rootContext()->setContextProperty("deckB", deckB.get());

    LibraryManager libraryManager;
    engine.rootContext()->setContextProperty("libraryManager", &libraryManager);

    LibraryDatabase libraryDb;
    if (!libraryDb.open())
        qWarning() << "[main] LibraryDatabase failed to open – library features disabled.";

    LibraryTableModel libraryTableModel("library_conn");
    libraryDb.setTableModel(&libraryTableModel);
    libraryTableModel.refresh();

    engine.rootContext()->setContextProperty("libraryDb",    &libraryDb);
    engine.rootContext()->setContextProperty("libraryModel", &libraryTableModel);

    deckA->setLibraryDatabase(&libraryDb);
    deckB->setLibraryDatabase(&libraryDb);

    FxManager fxManager;
    fxManager.registerEngines(deckA.get(), deckB.get());
    engine.rootContext()->setContextProperty("fxManager", &fxManager);

    LinkManager linkManager;
    engine.rootContext()->setContextProperty("linkManager", &linkManager);

    SystemMonitor sysMonitor;
    engine.rootContext()->setContextProperty("sysMonitor", &sysMonitor);

    engine.rootContext()->setContextProperty("parameterStore", &parameterStore);
    engine.rootContext()->setContextProperty("midiManager", &midiManager);

    const auto url = QUrl(u"qrc:/DJSoftware/src/qml/main.qml"_s);
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject* obj, const QUrl& objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);

    engine.load(url);

    if (!engine.rootObjects().isEmpty()) {
        if (auto* rootWindow = qobject_cast<QWindow*>(engine.rootObjects().first())) {
            qDebug() << "[main] Root window found, setting size and visibility";
            rootWindow->show();
            
#if defined(Q_OS_MACOS)
            // macOS requires extra steps to properly show the window
            rootWindow->raise();
            rootWindow->requestActivate();
            qDebug() << "[main] macOS: Window raised and activated";
#endif
        } else {
            qWarning() << "[main] Root object is not a QWindow!";
        }
    } else {
        qCritical() << "[main] No root objects found after loading QML!";
        return -1;
    }

    const int ret = app.exec();

    engine.rootContext()->setContextProperty("deckA", static_cast<QObject*>(nullptr));
    engine.rootContext()->setContextProperty("deckB", static_cast<QObject*>(nullptr));

    deckB.reset();
    deckA.reset();

    DjEngine::shutdownSharedAudioDeviceManager();

    juce::MessageManager::deleteInstance();
    juce::DeletedAtShutdown::deleteAll();

    return ret;
}
